[tasks.web]
dependencies = ["compile", "client"]

[tasks.compile]
script = '''
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-name penguinwars-io --out-dir assets --target web target/wasm32-unknown-unknown/release/penguinwars-io.wasm
'''

[tasks.client]
script = '''
basic-http-server .
'''